USE [master]
GO

/****** Object:  Database [fakeLookDB]    Script Date: 2/20/2020 12:26:03 AM ******/
CREATE DATABASE [fakeLookDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fakeLookDB_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\fakeLookDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'fakeLookDB_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\fakeLookDB.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [fakeLookDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fakeLookDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fakeLookDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fakeLookDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fakeLookDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fakeLookDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fakeLookDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [fakeLookDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fakeLookDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fakeLookDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fakeLookDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fakeLookDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fakeLookDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fakeLookDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fakeLookDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fakeLookDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fakeLookDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [fakeLookDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fakeLookDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fakeLookDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fakeLookDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fakeLookDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fakeLookDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fakeLookDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fakeLookDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [fakeLookDB] SET  MULTI_USER 
GO

ALTER DATABASE [fakeLookDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fakeLookDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fakeLookDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fakeLookDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [fakeLookDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fakeLookDB] SET QUERY_STORE = OFF
GO

USE [fakeLookDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [fakeLookDB] SET  READ_WRITE 
GO

